// Icons: Material (outlined) set, matching the design system. Names mirror the previous icon names so call-sites stay unchanged.
// To swap the icon family in future, change only this file.
export type { IconBaseProps as IconProps } from 'react-icons'
export { MdOutlineWarningAmber as AlertTriangle } from 'react-icons/md'
export { MdOutlineArrowForward as ArrowRight } from 'react-icons/md'
export { MdOutlineArrowUpward as ArrowUp } from 'react-icons/md'
export { MdOutlineWorkspacePremium as Award } from 'react-icons/md'
export { MdOutlineVerified as BadgeCheck } from 'react-icons/md'
export { MdOutlineNotificationsActive as BellRing } from 'react-icons/md'
export { MdOutlineMenuBook as BookOpen } from 'react-icons/md'
export { MdOutlineCalendarMonth as Calendar } from 'react-icons/md'
export { MdCheck as Check } from 'react-icons/md'
export { MdOutlineCheckCircle as CheckCircle2 } from 'react-icons/md'
export { MdOutlineKeyboardArrowDown as ChevronDown } from 'react-icons/md'
export { MdOutlineChevronLeft as ChevronLeft } from 'react-icons/md'
export { MdOutlineChevronRight as ChevronRight } from 'react-icons/md'
export { MdOutlineCircle as Circle } from 'react-icons/md'
export { MdOutlineAssignmentTurnedIn as ClipboardCheck } from 'react-icons/md'
export { MdOutlineCloudDone as CloudCheck } from 'react-icons/md'
export { MdOutlineContentCopy as Copy } from 'react-icons/md'
export { MdOutlineKeyboardReturn as CornerDownLeft } from 'react-icons/md'
export { MdOutlineCreditCard as CreditCard } from 'react-icons/md'
export { MdOutlineStorage as Database } from 'react-icons/md'
export { MdOutlineFileDownload as Download } from 'react-icons/md'
export { MdOutlineVisibility as Eye } from 'react-icons/md'
export { MdOutlineNoteAdd as FilePlus2 } from 'react-icons/md'
export { MdOutlineHistoryEdu as FileSignature } from 'react-icons/md'
export { MdOutlineDescription as FileText } from 'react-icons/md'
export { MdOutlineFingerprint as Fingerprint } from 'react-icons/md'
export { MdOutlineGavel as Gavel } from 'react-icons/md'
export { MdOutlineCardGiftcard as Gift } from 'react-icons/md'
export { MdOutlinePublic as Globe } from 'react-icons/md'
export { MdOutlineTag as Hash } from 'react-icons/md'
export { MdOutlineHistory as History } from 'react-icons/md'
export { MdOutlineInbox as Inbox } from 'react-icons/md'
export { MdOutlineInfo as Info } from 'react-icons/md'
export { MdOutlineLink as Link2 } from 'react-icons/md'
export { MdOutlineAutorenew as Loader2 } from 'react-icons/md'
export { MdOutlineMyLocation as LocateFixed } from 'react-icons/md'
export { MdOutlineMail as Mail } from 'react-icons/md'
export { MdOutlineLocationOn as MapPin } from 'react-icons/md'
export { MdOutlineMenu as Menu } from 'react-icons/md'
export { MdOutlineChatBubbleOutline as MessageCircle } from 'react-icons/md'
export { MdOutlineEdit as Pencil } from 'react-icons/md'
export { MdOutlineAdd as Plus } from 'react-icons/md'
export { MdOutlineFormatQuote as Quote } from 'react-icons/md'
export { MdOutlineReceiptLong as Receipt } from 'react-icons/md'
export { MdOutlineRocketLaunch as Rocket } from 'react-icons/md'
export { MdOutlineRssFeed as Rss } from 'react-icons/md'
export { MdOutlineBalance as Scale } from 'react-icons/md'
export { MdOutlineManageSearch as ScanSearch } from 'react-icons/md'
export { MdOutlineSearch as Search } from 'react-icons/md'
export { MdOutlineSearchOff as SearchX } from 'react-icons/md'
export { MdOutlineSend as Send } from 'react-icons/md'
export { MdOutlineShare as Share2 } from 'react-icons/md'
export { MdOutlineVerifiedUser as ShieldCheck } from 'react-icons/md'
export { MdOutlineGppBad as ShieldX } from 'react-icons/md'
export { MdOutlineSmartphone as Smartphone } from 'react-icons/md'
export { MdOutlineDelete as Trash2 } from 'react-icons/md'
export { MdOutlineLockOpen as Unlock } from 'react-icons/md'
export { MdOutlineCloudUpload as UploadCloud } from 'react-icons/md'
export { MdOutlinePerson as User } from 'react-icons/md'
export { MdOutlinePersonOff as UserX } from 'react-icons/md'
export { MdOutlineGroups as Users } from 'react-icons/md'
export { MdOutlineClose as X } from 'react-icons/md'
export { MdOutlineCancel as XCircle } from 'react-icons/md'
export { MdOutlineBolt as Zap } from 'react-icons/md'
export { MdOutlineStickyNote2 as StickyNote2, MdOutlineVerifiedUser as VerifiedUser, MdOutlinePrint as Printer, MdOutlineFileUpload as Upload } from 'react-icons/md'
export { MdOutlineAccountBalance as Bank, MdOutlineQrCode2 as QrCode, MdOutlinePayments as Payments, MdOutlineLock as Lock, MdOutlineWhatsapp as Whatsapp } from 'react-icons/md'
export { MdOutlineOpenInNew as OpenInNew, MdOutlineSchedule as Schedule, MdOutlineTravelExplore as Explore, MdOutlineKeyboardArrowUp as ArrowUpIcon, MdOutlineFactCheck as FactCheck } from 'react-icons/md'
export { MdOutlineKeyboardReturn as KeyboardReturn, MdOutlinePerson as Person, MdOutlineDescription as Description } from 'react-icons/md'
export { MdOutlineCampaign as Campaign, MdOutlineNotifications as Notifications, MdOutlineAnalytics as Analytics, MdOutlineSpeed as Speed, MdOutlineWorkspacePremium as Premium } from 'react-icons/md'
export { MdOutlineLockOpen as LockOpen, MdOutlineMilitaryTech as Medal, MdOutlineMenuBook as MenuBook, MdOutlineSensors as Live, MdOutlineCalculate as Calculator, MdOutlineFormatQuote as QuoteIcon } from 'react-icons/md'
export { MdOutlineFormatQuote as FormatQuote } from 'react-icons/md'
export { MdOutlinePause as Pause, MdOutlinePlayArrow as Play } from 'react-icons/md'
export { MdStar as Star } from 'react-icons/md'

export { MdOutlineLocalLibrary as LocalLibrary, MdOutlinePersonAdd as PersonAdd, MdOutlineLightbulb as Lightbulb, MdOutlineArrowBack as ArrowLeft, MdOutlineGppGood as GppGood, MdOutlineImage as ImageIcon, MdOutlineZoomOutMap as ZoomOut } from 'react-icons/md'
